### ISSUE TITLE
Retargeting Certain Animations Causes Floating Feet

### ISSUE THREAD

**Issue by stryker313** [smix8/GodotAnimationRetargeting#3] opened 2021-04-23 15:47 UTC
First off, absolutely love the module! Thanks! But, as per usual, first bugs I encountered.

Problem: Retargeting gltf animations causes the new animations to have floating feet, and be slightly messed up.
Settings: Godot 3.3, Using 2 of the same skeleton, exported as gltf, different animations. Retarget bone rotation enabled, custom rig types.
Settings and Solution Attempts: Have tried all the settings in different combinations, but no avail D:.
Observations: It looks like, (I could be wrong), that the retargeted animations are all based around the hips. I wonder if this is causing problem?

File for reference
[Animation Retarget.zip](https://github.com/smix8/GodotAnimationRetargeting/files/6366437/Animation.Retarget.zip)
Also video for reference: https://www.youtube.com/watch?v=ZggDMIXDHEw

This issue is minor in some cases, but in more extreme animations ex. longer punches, or longer leg movements, this problem becomes more extreme

Steps to Recreate: 
Import two gltf rigs, retarget animation from 1 model to the other, and the resulting animation has messed up feet.

I will note, that when I retargeted a mixamo to mixamo rig, everything worked fine. The mixamo rigs were also the exact same skeleton, and the same scale. The skeletons above are different scales, despite being same size(I increased the node scale for reference)

Thanks once again! This project is a huge help for a lot of people, and I'll do my best to keep reporting bugs!

**Comment by smix8** [comment] 2021-04-23 16:56
The used skeleton has no static root/hip bone. The source animation is changing the location of the root bone while the retargeting settings only retarget bone rotations but not positions.

![hipbone](https://user-images.githubusercontent.com/52464204/115903677-26d35100-a464-11eb-99e9-40ac10147324.gif)

If you turn on retarget_bone_position it will work for the hip bone but mess up all other bones in the skeleton.

The retargeting tool currently has no options to use different settings for different bones in a skeleton, it is all or nothing.

I am thinking of adding another `retarget_mode` option like `correction bone` only, so you can pick the hip bone, enable `retarget bone position` and change the animation without affecting the rest of the skeleton.

EDIT:
There is also the issue of scaling from outside the Skeleton. The retargeting tool is relying on the skeleton rest poses.

In your example the rest pose for the hipbone on the y-axis has a value of nearly 1.0 while on the small scale skeleton it is only 0.1. If we now retarget positions what will happen is that your entire skeleton will bet squashed to a 10% of its size cause the retargeting tool is reading a 90% position offset.

Godot does not update the rest bone values with scaling from outside so it is impossible for the retargeting tool to directly account for this.

**Comment by stryker313** [comment] 2021-04-23 18:50
I see. I'll have to work around until the new retarget mode then. :D. Do you think that it might be possible to retarget the animation once, then use the custom bone mapping to only retarget the hip bone with bone position?

**Comment by smix8** [comment] 2021-04-23 19:08
The issue is that the source animation is always copied in full first to also keep and copy method tracks, sound tracks, property tracks, ... and only then all the (bone) transform tracks are retargeted. If you add a single entry to the custom bone mapping all bones not included inside the dictionary are ignored for retargeting but this wouldn't prevent the animation track copy.

**Comment by smix8** [comment] 2021-04-24 13:50
After further investigation I have to say your skeleton is the perfect debug skeleton and I don't mean this in a mean way.

- It has a corrupted rest pose from import cause your animation data has overwritten the (original) rest pose of your skeleton.
- It has no static root bone, I postponed root_motion support cause it had issues but now I might as well add it back in.
- It has scaled skeletons from outside which messes up all the current bone positions calculations.

I will first add the root motion support as it requires the least UI work (which always takes way to much time) so this part should be ready soon.

**Comment by smix8** [comment] 2021-04-24 21:40
@stryker313

https://www.youtube.com/watch?v=XJ1az3CjAXU

Fixed the problems for this skeleton more or less but one issue remains. Scaling such a small skeleton adds a lot of precision errors. Some of the animation keyframes are in the low 0.001 range and scaling them can only get wrong and add small bone jitter.

**Comment by smix8** [comment] 2021-04-26 22:45
@stryker313 

I run into some bugs so I had to delay the upload a little. Progress can be seen here:
[Animation Retargeting Devlog #7](https://www.youtube.com/watch?v=Zr2CJpztYOI)

Whenever I "fix" root motion for all my own test skeletons your skeleton breaks. Whenever I fix your skeleton all my test skeletons break. I am not sure if it is just my mushy brain playing tricks on me. I mean I wasted 2 hours debugging today because Godot decided that copying a skeleton node should offset the rest poses of all bones on the new skeleton node by 0.002 for no reason.

**Comment by smix8** [comment] 2021-04-27 15:44
@stryker313 
Fixed by commit 460b1bb0ad9715724258438f09d2869f7a4a4402

I was able to fix your skeleton after using retargeting with `root_motion` enabled and with the correction mode to correct the hip bone down from the sky. Need to further investigate what is causing this aerial leap cause I couldn't reproduce this issue with my own skeletons. There are still small differences but I guess this is caused by precision problems due to the extreme scaling of x10. Let me know in a new issue if the added root motion is not working for you or has bugs.

**Closed as completed by smix8** 2021-04-27 15:44 UTC
Labels: documentation, enhancement
